module.exports = {
  dev: {
    PORT: 8012,
    APP_NAME: "xm_cpp_commnuity",
    WECHAT_APP_ID: "wxc08b67897a8587f7",
    WECHAT_DIRECT_URL: "https://dev-m-world.xiaomawang.com",
    BASE_URL: "https://dev-communityapi.xiaomawang.com",
    SSO_URL: "https://dev-sso.xiaomawang.com/login.html",
    XM_APP_ID: "xmw3851210656920",
    SSO_SCRIPT: "https://xmcdn.oss-cn-shanghai.aliyuncs.com/xm_sso_web/1.1.2/dev/login-sdk.js",
  },
  test: {
    PORT: 8012,
    APP_NAME: "xm_cpp_commnuity",
    WECHAT_APP_ID: "wxc08b67897a8587f7",
    WECHAT_DIRECT_URL: "https://test-m-world.xiaomawang.com",
    BASE_URL: "https://test-communityapi.xiaomawang.com",
    SSO_URL: "https://dev-sso.xiaomawang.com/login.html",
    XM_APP_ID: "xmw3851210656920",
    SSO_SCRIPT: "https://xmcdn.oss-cn-shanghai.aliyuncs.com/xm_sso_web/1.1.2/test/login-sdk.js",
  },
  test3: {
    PORT: 8012,
    APP_NAME: "xm_cpp_commnuity",
    WECHAT_APP_ID: "wxc08b67897a8587f7",
    WECHAT_DIRECT_URL: "https://test3-m-world.xiaomawang.com",
    BASE_URL: "https://test3-communityapi.xiaomawang.com",
    SSO_URL: "https://dev-sso.xiaomawang.com/login.html",
    XM_APP_ID: "xmw3851210656920",
    SSO_SCRIPT: "https://xmcdn.oss-cn-shanghai.aliyuncs.com/xm_sso_web/1.1.2/test/login-sdk.js",
  },
  gray: {
    PORT: 8012,
    APP_NAME: "xm_cpp_commnuity",
    WECHAT_APP_ID: "wx423812809045ac2b",
    WECHAT_DIRECT_URL: "https://gray-m-world.xiaomawang.com",
    BASE_URL: "https://dev-communityapi.xiaomawang.com",
    SSO_URL: "https://dev-sso.xiaomawang.com/login.html",
    XM_APP_ID: "xmw8066532241050",
    SSO_SCRIPT: "https://xmcdn.oss-cn-shanghai.aliyuncs.com/xm_sso_web/1.1.2/gray/login-sdk.js",
  },
  prod: {
    PORT: 8012,
    APP_NAME: "xm_cpp_commnuity",
    WECHAT_APP_ID: "wx423812809045ac2b",
    WECHAT_DIRECT_URL: "https://m-world.xiaomawang.com",
    BASE_URL: "https://dev-communityapi.xiaomawang.com",
    SSO_URL: "https://dev-sso.xiaomawang.com/login.html",
    XM_APP_ID: "xmw8066532241050",
    SSO_SCRIPT: "https://xmcdn.oss-cn-shanghai.aliyuncs.com/xm_sso_web/1.1.2/prod/login-sdk.js",
  }
}